[project]
name = "Boom"

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[[project.requirements]]
contract_id = "ST2PABAF9FTAJYNFZH93XENAJ8FVY99RRM4DF2YCW.nft-trait"

[contracts.boomboxes]
path = "contracts/boomboxes-18.clar"
depends_on = ["sip-9-nft-trait"]

[contracts.boom-nfts]
path = "contracts/boom-nfts-300.clar"
depends_on = []

# [contracts.boomboxes-admin]
# path = "contracts/boomboxes-admin.clar"
# depends_on = []

# [contracts.boomboxes-20]
# path = "contracts/boomboxes-20.clar"
# depends_on = ["boomboxes-admin"]

[contracts.sip-9-nft-trait]
path = "contracts/sips/sip-9-nft-trait.clar"
depends_on = []
