[project]
name = "boom.marketplace"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/Users/amrro/Developer/boom/boom-contracts/packages/boom-marketplace/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.boom-market]
path = "./contracts/boom-market-v1.clar"

[contracts.commission-trait]
path = "./contracts/commission.clar"

[contracts.mock-tradable-trait]
path = "contracts/mock-tradable-trait.clar"

[contracts.tradables-trait]
path = "./contracts/tradable-trait.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
