[project]
name = 'boombox-24'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'
requirements = []

[contracts.boombox]
path = 'contracts/boombox-28.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-30]
path = 'contracts/boombox-30.clar'
clarity_version = 1
epoch = 2.0
depends_on = ["nft-trait", "boombox-trait", "commission-trait"]

[contracts.boombox-32]
path = 'contracts/boombox-32.clar'
clarity_version = 1
epoch = 2.0
depends_on = ["nft-trait", "boombox-trait", "commission-trait"]

[contracts.boombox-34]
path = 'contracts/boombox-34.clar'
clarity_version = 1
epoch = 2.0
depends_on = ["nft-trait", "boombox-trait", "commission-trait"]

[contracts.boombox-36]
path = 'contracts/boombox-36.clar'
clarity_version = 1
epoch = 2.0
depends_on = ["nft-trait", "boombox-trait", "commission-trait"]
[contracts.boombox-38]

path = 'contracts/boombox-38.clar'
clarity_version = 1
epoch = 2.0
depends_on = ["nft-trait", "boombox-trait", "commission-trait"]
[contracts.boombox-40]

path = 'contracts/boombox-40.clar'
clarity_version = 1
epoch = 2.0
depends_on = ["nft-trait", "boombox-trait", "commission-trait"]

[contracts.boombox-42]
path = 'contracts/boombox-42.clar'
clarity_version = 1
epoch = 2.0
depends_on = ["nft-trait", "boombox-trait", "commission-trait"]
[contracts.boombox-44]

path = 'contracts/boombox-44.clar'
clarity_version = 1
epoch = 2.0
depends_on = ["nft-trait", "boombox-trait", "commission-trait"]

[contracts.boombox-46]
path = 'contracts/boombox-46.clar'
clarity_version = 1
epoch = 2.0
depends_on = ["nft-trait", "boombox-trait", "commission-trait"]

[contracts.boombox-48]
path = 'contracts/boombox-48.clar'
clarity_version = 1
epoch = 2.0
depends_on = ["nft-trait", "boombox-trait", "commission-trait"]
[contracts.boombox-50]

path = 'contracts/boombox-50.clar'
clarity_version = 1
epoch = 2.0
depends_on = ["nft-trait", "boombox-trait", "commission-trait"]

[contracts.boombox-admin]
path = '../boombox-admin/contracts/boombox-admin.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-simple]
path = '../boombox-admin/contracts/boombox-simple.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-trait]
path = '../boombox-admin/contracts/boombox-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.commission-trait]
path = '../common/contracts/commission.clar'
clarity_version = 1
epoch = 2.0

[contracts.nft-trait]
path = '../common/contracts/nft-trait.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
