[project]
name = 'Boomboxes'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[[project.requirements]]
contract_id = 'SP3D6PV2ACBPEKYJTCMH7HEN02KP87QSP8KTEH335.commission-trait'

[[project.requirements]]
contract_id = 'SPMS4E9RQ4GCGG68R6D15PKV01TYNCBPYZG1ZMFE.boombox-admin-v5'

[[project.requirements]]
contract_id = 'SPMS4E9RQ4GCGG68R6D15PKV01TYNCBPYZG1ZMFE.boombox-trait-v2'

[[project.requirements]]
[contracts.boombox-28]
path = 'contracts/boombox-28.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-30]
path = 'contracts/boombox-30.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-32]
path = 'contracts/boombox-32.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-34]
path = 'contracts/boombox-34.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-36]
path = 'contracts/boombox-36.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-38]
path = 'contracts/boombox-38.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-40]
path = 'contracts/boombox-40.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-42]
path = 'contracts/boombox-42.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-44]
path = 'contracts/boombox-44.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-46]
path = 'contracts/boombox-46.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-48]
path = 'contracts/boombox-48.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-50]
path = 'contracts/boombox-50.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-52]
path = 'contracts/boombox-52.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-54]
path = 'contracts/boombox-54.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-56]
path = 'contracts/boombox-56.clar'
clarity_version = 1
epoch = 2.0



[contracts.boombox-admin]
path = '../boombox-admin/contracts/boombox-admin.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-simple]
path = '../boombox-admin/contracts/boombox-simple.clar'
clarity_version = 1
epoch = 2.0

[contracts.boombox-trait]
path = '../boombox-admin/contracts/boombox-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.commission-trait]
path = '../common/contracts/commission.clar'
clarity_version = 1
epoch = 2.0

[contracts.commission-nop]
path = '../common/contracts/commission-nop.clar'
clarity_version = 1
epoch = 2.0

[contracts.nft-trait]
path = '../common/contracts/nft-trait.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
