[project]
name = "airdrop-moon"
authors = []
description = ""
telemetry = true
boot_contracts = ["pox", "costs-v2", "bns"]


[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"
[[project.requirements]]
contract_id = "SP2KAF9RF86PVX3NEE27DFV1CQX0T4WGR41X3S45C.commission-trait"

[contracts.test-mint]
path = "contracts/test-setup/test-mint.clar"
depends_on = []

[contracts.commission-free]
path = "contracts/test-setup/commission-free.clar"
depends_on = []

[contracts.moons-airdrop-mint]
path = "contracts/moons-airdrop-mint.clar"
depends_on = []


[contracts.moons-airdrop]
path = "contracts/moons-airdrop.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
