
[project]
name = "boom.money"


[[project.requirements]]
contract_id = "SP3C0TCQS0C0YY8E0V3EJ7V4X9571885D44M8EFWF.arkadiko-automation-trait-v1"

[contracts.boombox-admin]
path = "contracts/boombox-admin.clar"
depends_on = ["boombox-trait"]

[contracts.boombox-trait]
path = "contracts/boombox-trait.clar"
depends_on = []

[contracts.boombox-simple]
path = "contracts/boombox-simple.clar"
depends_on = []

[contracts.boombox-auto]
path = "contracts/boombox-auto.clar"
depends_on = []

[notebooks]
